version: '3.9'
services:
  dev:
    build: .
    volumes:
      - ./:/src # Mount local source code into the contianer
      - ~/.ssh:/root/.ssh # For github auth usage
    ports:
    - 3000:3000 # Default md serve
    command: mdbook serve -n 0.0.0.0